d/tests/installed-tests: Ignore test failures on some architectures
These are the same architectures where we don't run build-time tests.
On s390x the tests are timing out at the default 5 minute cutoff, and
it's not clear whether they would finish successfully if allowed to
run for longer.

diff --git a/debian/tests/installed-tests b/debian/tests/installed-tests
--- a/debian/tests/installed-tests
+++ b/debian/tests/installed-tests
@@ -15,7 +15,21 @@ if [ -z "$(ginsttest-runner -l "$namespace")" ]; then
     exit 1
 fi
 
-exec ginsttest-runner \
+e=0
+ginsttest-runner \
     --log-directory "$AUTOPKGTEST_ARTIFACTS" \
     --tap \
-    "$namespace"
+    "$namespace" || e="$?"
+
+if [ "$e" -ne 0 ]; then
+    arch="$(dpkg --print-architecture)"
+    case "$arch" in
+        # Please keep this list in sync with debian/rules
+        (mips|mips64el|mipsel|riscv64|s390x|alpha|hppa|powerpc|sparc64|x32)
+            echo "# Ignoring test failure on $arch"
+            exit 77
+            ;;
+    esac
+
+    exit "$e"
+fi
